# Service
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np-svc
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 31900
     protocol: TCP

# Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - containerPort: 80
